apiVersion: apps/v1
kind: Deployment
metadata:
  name: threat-api
  lebels:
    app: threat-api
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: threat-api
  template:
    metadata:
      labels:
        app: threat-api
    spec:
      containers:
        - name: threat-api
          image: moshe5434/threat-api:v1
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_HOST
              value: "mongo-0.mongo"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: "admin"
            - name: MONGO_PAASWORD
              value: "secretpass"
            - name: MONGO_DB
              value: "threat_db"
            - name: MONGO_AUTH_SOURCE
              value: "admin"

              
   